Característica: Añadir nuevas referencias
aulasoftwarelibre/taller-de-git pull request #2
Opened 2017-11-27 21:49 UTC by juancoob

Nuevas referencias  para seguir aprendiendo

2017-11-29 22:58 UTC, sgomez commented
Gracias @juancoob pero has añadido como referencia al propio curso del aula... ¡Referencia recursiva! Si lo quitas lo mezclo.

2017-11-29 23:00 UTC, sgomez requested changes
Gracias @juancoob pero has añadido como referencia al propio curso del aula... ¡Referencia recursiva! Si lo quitas lo mezclo.

2017-11-29 23:00 UTC, sgomez commented on docs/referencias.md
> +* [Curso detallado y gratuito sobre Git y github](https://www.uco.es/aulasoftwarelibre/curso-de-git/)
Es el propio curso.

2017-11-30 07:49 UTC, juancoob commented on docs/referencias.md
> +* [Curso detallado y gratuito sobre Git y github](https://www.uco.es/aulasoftwarelibre/curso-de-git/)
vaya, una metedura de pata jaja

2017-12-01 06:55 UTC, sgomez approved these changes

2017-12-01 06:56 UTC, merged